baseURL = "http://grant.dev"
languageCode = "en-us"
title = "Grant Ammons"
theme = "blank"
copyright = "&copy; Copyright 2020 by Grant Ammons"
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About me"
    title = "About me"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    title = "Portfolio"
    url = "/portfolio/"
    weight = -110

[params]
  [[params.social]]
    fa_icon = "fa fa-github"
    href = "http://github.com/gammons"
  [[params.social]]
    fa_icon = "fa fa-linkedin"
    href = "https://www.linkedin.com/in/grant-ammons"
  [[params.social]]
    fa_icon = "fa fa-twitter"
    href = "https://twitter.com/gammons"
  [[params.social]]
    fa_icon = "fa fa-medium"
    href = "https://medium.com/@gammons"
  [[params.social]]
    fa_icon = "fa fa-envelope"
    href = "mailto:grant@grant.dev"
